Minor changes after review

diff --git a/ci/pipelines/linters.yaml b/ci/pipelines/linters.yaml
--- a/ci/pipelines/linters.yaml
+++ b/ci/pipelines/linters.yaml
@@ -3,13 +3,14 @@ trigger:
   branches:
     include:
     - develop
+
 pr:
   branches:
     include:
     - develop
 
 pool:
-  name: $(poolName)
+  name: $(agentPoolName)
 
 variables:
   ansible_lint_error_threshold: 730
@@ -26,39 +27,49 @@ jobs:
     # To be compatible with the epicli's parent image (python:3.10-slim).
     inputs:
       versionSpec: 3.10
+
   - task: Bash@3
-    displayName: Install Ansible Linter and its dependencies
+    displayName: Install Ansible Lint and its dependencies
     inputs:
       targetType: inline
       script: |
         pip install --upgrade ansible ansible-lint ansible-lint-junit==0.16 lxml pip setuptools
+
   - task: Bash@3
-    displayName: Run Ansible Linter
+    displayName: Run Ansible Lint
     inputs:
       targetType: inline
       script: |
-        ansible-lint --nocolor > ansible_lint_errors
-        # Suppress the next line when the "load-failure" bug in ansible-lint is solved
-        # https://github.com/ansible-community/ansible-lint/issues/1446
-        sed -i '/load-failure/d' ansible_lint_errors
-        error_count=$(wc -l ansible_lint_errors | awk '{ print $1 }')
-        # Convert to junit
-        ansible-lint-junit ansible_lint_errors -o ansible_lint_errors.xml
-        test $error_count -le $(ansible_lint_error_threshold)
+        set -e
+        if ansible-lint --nocolor 1> ansible_lint_stdout 2> ansible_lint_stderr \
+        || grep 'violation(s) that are fatal' ansible_lint_stderr; then
+          # Suppress the next line when the "load-failure" bug in ansible-lint is solved
+          # https://github.com/ansible-community/ansible-lint/issues/1446
+          sed -i '/load-failure/d' ansible_lint_stdout
+          error_count=$(wc -l ansible_lint_stdout | awk '{ print $1 }')
+          # Convert to junit
+          ansible-lint-junit ansible_lint_stdout -o ansible_lint_output.xml
+          test $error_count -le $(ansible_lint_error_threshold)
+        else
+          exit 1
+        fi
+
   - task: PublishTestResults@2
-    displayName: Publish Ansible Linting Test Results
+    displayName: Publish Ansible Lint test results
     inputs:
-      testResultsFiles: ansible_lint_errors.xml
+      testResultsFiles: ansible_lint_output.xml
       searchFolder: $(System.DefaultWorkingDirectory)
-      testRunTitle: Ansible Linting Test Results
+      testRunTitle: Ansible Lint test results
+
   - task: Bash@3
-    displayName: Install Python dependencies and its dependencies
+    displayName: Install Pylint and its dependencies
     inputs:
       targetType: inline
       script: |
         pip install --upgrade pylint pylint-fail-under pylint-junit
+
   - task: Bash@3
-    displayName: Run Python Linter on CLI code
+    displayName: Run Pylint on CLI code
     inputs:
       targetType: inline
       script: |
@@ -66,38 +77,44 @@ jobs:
         --rcfile .pylintrc \
         --fail-under=$(pylint_score_cli_threshold) \
         --output cli_code_results.xml
+
   - task: PublishTestResults@2
-    displayName: Publish Python Linting Test Results for CLI Code
+    displayName: Publish Pylint test results for CLI Code
     inputs:
       testResultsFiles: cli_code_results.xml
       searchFolder: $(System.DefaultWorkingDirectory)
-      testRunTitle: Python Linting Test Results for CLI Code
+      testRunTitle: Pylint test results for CLI Code
+
   - task: Bash@3
-    displayName: Run Python Linter on Test Code
+    displayName: Run Pylint on test code
     inputs:
       targetType: inline
       script: |
-        python -m pylint ./tests \
+        pylint ./tests \
         --rcfile .pylintrc \
         --fail-under=$(pylint_score_tests_threshold) \
         --output test_code_results.xml \
         --disable=F0401 # Disable import-error checking
+
   - task: PublishTestResults@2
-    displayName: Publish Python Linting Test Results for Test Code
+    displayName: Publish Pylint test results for test code
     inputs:
       testResultsFiles: test_code_results.xml
       searchFolder: $(System.DefaultWorkingDirectory)
-      testRunTitle: Python Linting Test Results for Test Code
+      testRunTitle: Pylint test results for test code
+
   - task: Bash@3
     displayName: Install Rubocop and its dependencies
     inputs:
       targetType: inline
       script: |
-        apt-get -y update \
-        && apt-get -y install rubygems \
-        && gem install rubocop-ast:1.17.0 rubocop:1.28.2 rubocop-junit_formatter
+        set -e
+        apt-get -y update
+        apt-get -y install rubygems
+        gem install rubocop-ast:1.17.0 rubocop:1.28.2 rubocop-junit_formatter
+
   - task: Bash@3
-    displayName: Run Rubocop linter on Test Code
+    displayName: Run Rubocop linter on test code
     inputs:
       targetType: inline
       script: |
@@ -107,23 +124,25 @@ jobs:
         --format RuboCop::Formatter::JUnitFormatter \
         --out rubocop_results.xml \
         --fail-level error
+
   - task: Bash@3
     displayName: Assert number of linter failures
     inputs:
       targetType: inline
       script: |
+        set -e
         # Fetch number of detected failures from results file, then test if it does not exceed the declared threshold
         # rubocop_linter_threshold is set based on latest linter results performed after code cleaning
-        set -e
         detected_failures=$( \
           grep --only-matching 'failures=.[0-9]*.' rubocop_results.xml | \
           grep --only-matching '[0-9]*')
         echo "Number of detected failures: $detected_failures"
         echo "Failures threshold value: $(rubocop_linter_threshold)"
         test $detected_failures -le $(rubocop_linter_threshold)
+
   - task: PublishTestResults@2
-    displayName: Publish Rubocop Linting Test Results
+    displayName: Publish Rubocop linting test results
     inputs:
       testResultsFiles: rubocop_results.xml
       searchFolder: $(System.DefaultWorkingDirectory)
-      testRunTitle: Rubocop Test Results
+      testRunTitle: Rubocop linting test results
